### ISSUE TITLE
Import failed! Reason: Value cannot be an empty collection. Parameter name: resources

### ISSUE THREAD

**Issue by Oudiii** [valdisiljuconoks/localization-provider-opti#78]
v. 6.2.0

I've got a really small set of localized values (en, fi for now) in my local env
-> Export values (fine)
-> Modify couple of values in the JSON file
-> Import preview (fine, it shows the correct changes)
-> Start import with all changes gives the error "Import failed! Reason: Value cannot be an empty collection. Parameter name: resources"

However the values changed in the JSON still seem to get updated.

So any idea why is it giving the error?

**Comment by valdisiljuconoks** [comment]
Got stack trace in episerver log file?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Oudiii** [comment]
This seems to be only one appearing, but i doubt its relevant here, because its not appearing all the time as the message in the admin ui is? Should there be some additional configuration done related to logging ?

2020-09-18 12:29:08,726 [5] ERROR EPiServer.DataAccess.Internal.JsonPropertyValueConverter: An exception occurred while converting JSON property
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

**Comment by valdisiljuconoks** [comment]
No, I don’t think there is anything else to enable. Need to check logging functionality on AdminUI (I know that I’ve been lazy there).


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
